### ISSUE TITLE
abbreviation not displaying on ST 3

### ISSUE THREAD

**Issue by nalagg** [emmetio/sublime-text-plugin#110] opened 2020-09-02 19:00 UTC
I am having a similar issue as: https://github.com/emmetio/sublime-text-plugin/issues/71
when I try to abbreviate, the code hint does not display and complex shorthand such as 
`nav>ul>li` produces `nav>ul><li></li>`
here are my settings
`{
	"detect_indentation": false,
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage"
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
`

**Comment by yayayahahaha** [comment] 2020-09-03 06:04
I guess I can reproduce the error.
type `nav`, I got this:

<ins>nav</ins>

there's an underline under the text I just type.
I press `esc`, the underline is disappear.
then, I type `>ul`, I got this

nav><ins>ul</ins>

the underline is only appear under `ul`.
in this status, if I run `expand abbreviation` command,
I got this:

`nav><ul></ul>`

for this example, if I create something like `nav>ul>li` without any underline of them.
the expand abbreviation result is

`nav>ul><li></li>`

it seems the expand abbreviation only works with continued typing.
if some how the typing is interrupted, the expand will only work with the underline-part,
or without underline, the last one will be expand.

**Comment by sergeche** [comment] 2020-09-03 08:36
@yayayahahaha Yes, this is how new Emmet version works: https://github.com/emmetio/sublime-text-plugin#expanding-abbreviation
If you hit Esc, you say that you don’t want typed word to be expanded as Emmet abbreviation and Tab should run normally (expand native ST snippet, insert Tab, etc.). If you want to continue abbreviation typing, you should capture it first with Ctrl-Space, as described in README

**Comment by sergeche** [comment] 2020-09-19 16:55
Closing for now, seems to be an issue with abbreviation continuation. Another option for this case is to put caret after existing abbreviation and run `Emmet: Capture Abbreviation` action: it will try to find abbreviation left to caret location and capture it (add underline) so you can continue with editing

**Closed by sergeche** 2020-09-19 16:55 UTC
