### ISSUE TITLE
expand abbreviation on multiple lines

### ISSUE THREAD

**Issue by bquarante** [emmetio/sublime-text-plugin#107] opened 2020-09-02 10:29 UTC
Hello,

i have a recent issue with the update, i can't use the expand abbreviation on several lines, it expands only the first line.

Thanks a lot,
Bernard

**Comment by yayayahahaha** [comment] 2020-09-03 05:47
Probably duplicate of #69

**Closed** 2020-09-03 08:00 UTC
