### ISSUE TITLE
Last update breaks twig conditions

### ISSUE THREAD

**Issue by or3lie** [emmetio/sublime-text-plugin#95] opened 2020-08-28 13:39 UTC
Hello,

I noticed that the last update breaks my twig conditions.

For exemple if I want to write a twig condition like that :
`{% if someCondition.something %}{% endif %}`
when I type the point my condition becomes
`{% if someCondition class="" %}{% endif %}`

So I can't write my twig conditions anymore :(

Thanks for your help

**Comment by sergeche** [comment] 2020-08-28 13:44
Duplicate of https://github.com/emmetio/sublime-text-plugin/issues/91

**Closed** 2020-08-30 09:46 UTC
