### ISSUE TITLE
Really slow / laggy Emmet in bigger CSS files?

### ISSUE THREAD

**Issue by mklusak** [emmetio/sublime-text-plugin#143] opened 2020-11-20 09:11 UTC
A few weeks ago (?) I noticed Sublime Text 3 slows down when typing CSS code in CSS file with 2-3000 lines of code. For example I write "body", and it is not typed out by one letter at a time, it appears as "body" after approx 1 second.  After adding brackets, I write "tac" and hit Tab, and it expands to "text-align: center" after same delay, without even seeing "tac" being typed out, and without that new green ... suggestion bubble or what. 

But if I try exactly this at the beggining of the same file, it works as fast as usual. 

Just typing out selectors alone is slow and behaves like described above. After Emmet package disabling, typing anything is fast as expected. After re-enabling, typing and expanding is lagging. Bigged the file, the slower typing became.

Where could be a problem?

**Comment by sergeche** [comment] 2020-11-20 09:13
Can you provide example of such file?

**Comment by mklusak** [comment] 2020-11-20 09:20
Here - https://tmpfiles.org/download/100366/style.css (some 2 hour temporary link)

It's not top notch styled code, and I use massive commented ASCII headers (to see them in minimap) ... I tried to remove them, but it had no effect.

**Comment by cupok** [comment] 2020-11-23 15:33
I have came issue

**Comment by Brittliff** [comment] 2020-11-30 20:45
Setting `auto_mark` to `"markup"` or `false` in the options fixes this for me.

**Comment by mklusak** [comment] 2020-12-01 05:59
@Brittliff Yeah, confirming ... but what's the point of having Emmet installed without its abbreviations expanding? :-)

**Comment by Brittliff** [comment] 2020-12-01 06:31
Oh apologies @mklusak, I didn't even realise that setting completely disabled Emmet haha. I must have misread the description. 

I don't actually use Emmet for CSS, so hopefully it helps someone else like me with a temporary workaround at least. 😅

**Comment by sergeche** [comment] 2020-12-01 12:51
Just published v2.3.0, should work better with large CSS codebase.

FYI: the problem is how Emmet detects if it should provide completions for given location. E.g. it checks if you’re going to write CSS property, not CSS selector or property value. Since ST doesn’t provide object model for document structure analysis, Emmet has to re-parse document to check if you’re in allowed context to expand abbreviation.

In v2.3.0, I was able to implement context detection using native ST API, which works really fast. Yet it fails in preprocessors like SCSS and LESS due to edge cases like this: `foo { p| }` — ST reports `p` is a (nested) selector, which is forbidden scope for Emmet, yet Emmet parser detects it’s likely a property. 

So, fast context detection currently works for pure CSS, for preprocessors it uses slow parser.

**Comment by mklusak** [comment] 2020-12-01 15:34
Hi, @sergeche, I wanted to write "Awesome!", but ... it does not work at all, now. I updated Emmet plugin to 2.3.0, and its suggestions and completions in my style.css have disappeared. Writing "body { tac + TAB}" does nothing (add tab space). Style.scss works, by the way (but as slow as before).

Should I do something more? Some config update, etc.?

**Comment by sergeche** [comment] 2020-12-01 15:38
@mklusak it happens in your large file or in clean CSS file?

**Comment by mklusak** [comment] 2020-12-01 15:42
@sergeche  Both.

**Comment by sergeche** [comment] 2020-12-01 15:45
Works fine for me. Can you open ST console and check if there are any errors?

**Comment by sergeche** [comment] 2020-12-01 15:45
Also, can you show me your Emmet config?

**Comment by mklusak** [comment] 2020-12-01 15:48
Aaah, there could be some culprit, console says _Unable to open /C/Users/marek/AppData/Roaming/Sublime Text 3/Packages/Emmet/Emmet.sublime-settings_ ...

**Comment by sergeche** [comment] 2020-12-01 15:57
Hm, weird. Could you remove and install Emmet package?

**Comment by mklusak** [comment] 2020-12-01 16:02
I restarted my PC, it didn't help.

I removed package, and re-installed, everything is the same. Console does not show any errors, only that "unable to open ..." mentioned earlier. And really, I don't have any Emmet folder in /C/Users/marek/AppData/Roaming/Sublime Text 3/Packages/ ...

**Comment by sergeche** [comment] 2020-12-01 16:22
If Emmet works in SCSS then it's not the issue. It might happen if something wrong with plugin.

Also, do you use default CSS highlighter or custom plugin?

**Comment by mklusak** [comment] 2020-12-01 16:27
Well, I really don't know :-) I set up my Sublime text years ago ... below is my console content after start, so maybe there is something about it:



DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/marek/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/marek/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/marek/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Text Pastry", "Vintage"]
pre session restore time: 0.664531
warning: mnemonic t not found in menu caption Tools
warning: mnemonic f not found in menu caption WordPress Developer Resources
startup time: 0.776531
first paint time: 0.777531
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin Emmet.main
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SCSS.scss_completions
reloading plugin String 2 Lower Hyphen.String2LowerHyphen
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter._init
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Tabright.Tabright
reloading plugin WordPress Developer Resources.SublimeWPDeveloperResources
reloading plugin LiveStyle.livestyle-plugin
plugins loaded
LiveStyle: Start app
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
Package Control: No updated packages

**Comment by sergeche** [comment] 2020-12-01 16:32
It could be SCSS package, check which syntax is displayed in lower right corner of ST when you work with CSS

**Comment by mklusak** [comment] 2020-12-01 16:44
Syntax is correct, it's CSS.

I did find something! If I write "body {tac + TAB }", it does nothing. BUT if I place caret like this "body { ta|c }" and hit TAB, it expands somehow:

![image](https://user-images.githubusercontent.com/3023092/100769706-b7998980-33fc-11eb-8d1b-9463d73376e1.png)

**Comment by sergeche** [comment] 2020-12-02 20:48
Just checked it out: the problem happens with exactly this code format

```css
body { | }
```

E.g. when selector and braces are on the same line and there are spaces before and after cursor. For some reason ST doesn’t report proper scope for this case.

With this formatting everything works fine:

```css
body {
   |
}

body {|}
```

Gotta find another way to fast parse contents

**Comment by mklusak** [comment] 2020-12-03 05:55
Ah, here comes the reason to finally leave my ugly "compressed" formatting :-)

**Comment by sergeche** [comment] 2020-12-13 16:09
Issue with `body { | }` should be fixed in v.2.3.1

**Comment by mklusak** [comment] 2020-12-14 09:12
Hi @sergeche, it looks good! Thank you!

**Closed** 2020-12-14 09:14 UTC
